# Generated by Django 5.2.7 on 2025-11-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_composition',
            new_name='total_compensation',
        ),
    ]
